// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: VideoService.proto

package videoSvcPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//--------------------------------video--------------------------------
type PubVideoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthId   int64  `protobuf:"varint,1,opt,name=AuthId,proto3" json:"AuthId,omitempty"`    //authId
	Title    string `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`       //title
	PlayURL  string `protobuf:"bytes,3,opt,name=PlayURL,proto3" json:"PlayURL,omitempty"`   //play_url
	CoverURL string `protobuf:"bytes,4,opt,name=CoverURL,proto3" json:"CoverURL,omitempty"` //cover_url
}

func (x *PubVideoReq) Reset() {
	*x = PubVideoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VideoService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubVideoReq) ProtoMessage() {}

func (x *PubVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_VideoService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubVideoReq.ProtoReflect.Descriptor instead.
func (*PubVideoReq) Descriptor() ([]byte, []int) {
	return file_VideoService_proto_rawDescGZIP(), []int{0}
}

func (x *PubVideoReq) GetAuthId() int64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

func (x *PubVideoReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PubVideoReq) GetPlayURL() string {
	if x != nil {
		return x.PlayURL
	}
	return ""
}

func (x *PubVideoReq) GetCoverURL() string {
	if x != nil {
		return x.CoverURL
	}
	return ""
}

type PubVideoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PubVideoResp) Reset() {
	*x = PubVideoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VideoService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubVideoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubVideoResp) ProtoMessage() {}

func (x *PubVideoResp) ProtoReflect() protoreflect.Message {
	mi := &file_VideoService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubVideoResp.ProtoReflect.Descriptor instead.
func (*PubVideoResp) Descriptor() ([]byte, []int) {
	return file_VideoService_proto_rawDescGZIP(), []int{1}
}

type Video struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                       //id
	Title         string `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`                  //title
	PlayURL       string `protobuf:"bytes,3,opt,name=PlayURL,proto3" json:"PlayURL,omitempty"`              //play_url
	CoverURL      string `protobuf:"bytes,4,opt,name=CoverURL,proto3" json:"CoverURL,omitempty"`            //cover_url
	FavoriteCount int64  `protobuf:"varint,5,opt,name=FavoriteCount,proto3" json:"FavoriteCount,omitempty"` //favorite_count
	CommentCount  int64  `protobuf:"varint,6,opt,name=CommentCount,proto3" json:"CommentCount,omitempty"`   //comment_count
	IsFavorite    bool   `protobuf:"varint,7,opt,name=IsFavorite,proto3" json:"IsFavorite,omitempty"`       //is_favorite
	AuthId        int64  `protobuf:"varint,8,opt,name=AuthId,proto3" json:"AuthId,omitempty"`               // auth_id
}

func (x *Video) Reset() {
	*x = Video{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VideoService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_VideoService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_VideoService_proto_rawDescGZIP(), []int{2}
}

func (x *Video) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetPlayURL() string {
	if x != nil {
		return x.PlayURL
	}
	return ""
}

func (x *Video) GetCoverURL() string {
	if x != nil {
		return x.CoverURL
	}
	return ""
}

func (x *Video) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

func (x *Video) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Video) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

func (x *Video) GetAuthId() int64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

type GetVideoListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthId int64 `protobuf:"varint,1,opt,name=AuthId,proto3" json:"AuthId,omitempty"` //authId
}

func (x *GetVideoListReq) Reset() {
	*x = GetVideoListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VideoService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoListReq) ProtoMessage() {}

func (x *GetVideoListReq) ProtoReflect() protoreflect.Message {
	mi := &file_VideoService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoListReq.ProtoReflect.Descriptor instead.
func (*GetVideoListReq) Descriptor() ([]byte, []int) {
	return file_VideoService_proto_rawDescGZIP(), []int{3}
}

func (x *GetVideoListReq) GetAuthId() int64 {
	if x != nil {
		return x.AuthId
	}
	return 0
}

type GetVideoListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoPubList []*Video `protobuf:"bytes,1,rep,name=VideoPubList,proto3" json:"VideoPubList,omitempty"` //video_list
}

func (x *GetVideoListResp) Reset() {
	*x = GetVideoListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VideoService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoListResp) ProtoMessage() {}

func (x *GetVideoListResp) ProtoReflect() protoreflect.Message {
	mi := &file_VideoService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoListResp.ProtoReflect.Descriptor instead.
func (*GetVideoListResp) Descriptor() ([]byte, []int) {
	return file_VideoService_proto_rawDescGZIP(), []int{4}
}

func (x *GetVideoListResp) GetVideoPubList() []*Video {
	if x != nil {
		return x.VideoPubList
	}
	return nil
}

type FeedVideosReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastTime int64 `protobuf:"varint,1,opt,name=LastTime,proto3" json:"LastTime,omitempty"` // last_time
}

func (x *FeedVideosReq) Reset() {
	*x = FeedVideosReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VideoService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedVideosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedVideosReq) ProtoMessage() {}

func (x *FeedVideosReq) ProtoReflect() protoreflect.Message {
	mi := &file_VideoService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedVideosReq.ProtoReflect.Descriptor instead.
func (*FeedVideosReq) Descriptor() ([]byte, []int) {
	return file_VideoService_proto_rawDescGZIP(), []int{5}
}

func (x *FeedVideosReq) GetLastTime() int64 {
	if x != nil {
		return x.LastTime
	}
	return 0
}

type FeedVideosResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoPubList []*Video `protobuf:"bytes,1,rep,name=VideoPubList,proto3" json:"VideoPubList,omitempty"` //video_list
	NextTime     int64    `protobuf:"varint,2,opt,name=NextTime,proto3" json:"NextTime,omitempty"`        // next_time
}

func (x *FeedVideosResp) Reset() {
	*x = FeedVideosResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VideoService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedVideosResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedVideosResp) ProtoMessage() {}

func (x *FeedVideosResp) ProtoReflect() protoreflect.Message {
	mi := &file_VideoService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedVideosResp.ProtoReflect.Descriptor instead.
func (*FeedVideosResp) Descriptor() ([]byte, []int) {
	return file_VideoService_proto_rawDescGZIP(), []int{6}
}

func (x *FeedVideosResp) GetVideoPubList() []*Video {
	if x != nil {
		return x.VideoPubList
	}
	return nil
}

func (x *FeedVideosResp) GetNextTime() int64 {
	if x != nil {
		return x.NextTime
	}
	return 0
}

type MyFavoriteVideosReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoIdArr []int64 `protobuf:"varint,1,rep,packed,name=VideoIdArr,proto3" json:"VideoIdArr,omitempty"` //videos_id
}

func (x *MyFavoriteVideosReq) Reset() {
	*x = MyFavoriteVideosReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VideoService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyFavoriteVideosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyFavoriteVideosReq) ProtoMessage() {}

func (x *MyFavoriteVideosReq) ProtoReflect() protoreflect.Message {
	mi := &file_VideoService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyFavoriteVideosReq.ProtoReflect.Descriptor instead.
func (*MyFavoriteVideosReq) Descriptor() ([]byte, []int) {
	return file_VideoService_proto_rawDescGZIP(), []int{7}
}

func (x *MyFavoriteVideosReq) GetVideoIdArr() []int64 {
	if x != nil {
		return x.VideoIdArr
	}
	return nil
}

type MyFavoriteVideosResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoPubList []*Video `protobuf:"bytes,1,rep,name=VideoPubList,proto3" json:"VideoPubList,omitempty"` //video_list
}

func (x *MyFavoriteVideosResp) Reset() {
	*x = MyFavoriteVideosResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_VideoService_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyFavoriteVideosResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyFavoriteVideosResp) ProtoMessage() {}

func (x *MyFavoriteVideosResp) ProtoReflect() protoreflect.Message {
	mi := &file_VideoService_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyFavoriteVideosResp.ProtoReflect.Descriptor instead.
func (*MyFavoriteVideosResp) Descriptor() ([]byte, []int) {
	return file_VideoService_proto_rawDescGZIP(), []int{8}
}

func (x *MyFavoriteVideosResp) GetVideoPubList() []*Video {
	if x != nil {
		return x.VideoPubList
	}
	return nil
}

var File_VideoService_proto protoreflect.FileDescriptor

var file_VideoService_proto_rawDesc = []byte{
	0x0a, 0x12, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x71, 0x0a, 0x0b, 0x50, 0x75, 0x62, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x41, 0x75, 0x74, 0x68, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x6c, 0x61, 0x79, 0x55, 0x52, 0x4c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x6c, 0x61, 0x79, 0x55, 0x52, 0x4c, 0x12,
	0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x22, 0x0e, 0x0a, 0x0c, 0x50,
	0x75, 0x62, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0xe5, 0x01, 0x0a, 0x05,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x50,
	0x6c, 0x61, 0x79, 0x55, 0x52, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x6c,
	0x61, 0x79, 0x55, 0x52, 0x4c, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x55, 0x52,
	0x4c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x55, 0x52,
	0x4c, 0x12, 0x24, 0x0a, 0x0d, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69,
	0x74, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x49,
	0x73, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0a, 0x49, 0x73, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41,
	0x75, 0x74, 0x68, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x41, 0x75, 0x74,
	0x68, 0x49, 0x64, 0x22, 0x29, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x41, 0x75, 0x74, 0x68, 0x49, 0x64, 0x22, 0x41,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x2d, 0x0a, 0x0c, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x50, 0x75, 0x62, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x52, 0x0c, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x50, 0x75, 0x62, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x2b, 0x0a, 0x0d, 0x46, 0x65, 0x65, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x4c, 0x61, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x5b,
	0x0a, 0x0e, 0x46, 0x65, 0x65, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x2d, 0x0a, 0x0c, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x50, 0x75, 0x62, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x52, 0x0c, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x50, 0x75, 0x62, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x4e, 0x65, 0x78, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x4e, 0x65, 0x78, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x35, 0x0a, 0x13, 0x4d,
	0x79, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x41, 0x72, 0x72,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x41,
	0x72, 0x72, 0x22, 0x45, 0x0a, 0x14, 0x4d, 0x79, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x0c, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x50, 0x75, 0x62, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x0c, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x50, 0x75, 0x62, 0x4c, 0x69, 0x73, 0x74, 0x32, 0xf7, 0x01, 0x0a, 0x0c, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x50, 0x75,
	0x62, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x62, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x62,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x14,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0a, 0x46, 0x65, 0x65, 0x64, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x73, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x48, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x4d, 0x79, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73,
	0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x79, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x4d,
	0x79, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x76,
	0x63, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_VideoService_proto_rawDescOnce sync.Once
	file_VideoService_proto_rawDescData = file_VideoService_proto_rawDesc
)

func file_VideoService_proto_rawDescGZIP() []byte {
	file_VideoService_proto_rawDescOnce.Do(func() {
		file_VideoService_proto_rawDescData = protoimpl.X.CompressGZIP(file_VideoService_proto_rawDescData)
	})
	return file_VideoService_proto_rawDescData
}

var file_VideoService_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_VideoService_proto_goTypes = []interface{}{
	(*PubVideoReq)(nil),          // 0: pb.PubVideoReq
	(*PubVideoResp)(nil),         // 1: pb.PubVideoResp
	(*Video)(nil),                // 2: pb.Video
	(*GetVideoListReq)(nil),      // 3: pb.GetVideoListReq
	(*GetVideoListResp)(nil),     // 4: pb.GetVideoListResp
	(*FeedVideosReq)(nil),        // 5: pb.FeedVideosReq
	(*FeedVideosResp)(nil),       // 6: pb.FeedVideosResp
	(*MyFavoriteVideosReq)(nil),  // 7: pb.MyFavoriteVideosReq
	(*MyFavoriteVideosResp)(nil), // 8: pb.MyFavoriteVideosResp
}
var file_VideoService_proto_depIdxs = []int32{
	2, // 0: pb.GetVideoListResp.VideoPubList:type_name -> pb.Video
	2, // 1: pb.FeedVideosResp.VideoPubList:type_name -> pb.Video
	2, // 2: pb.MyFavoriteVideosResp.VideoPubList:type_name -> pb.Video
	0, // 3: pb.VideoService.PubVideo:input_type -> pb.PubVideoReq
	3, // 4: pb.VideoService.GetVideoList:input_type -> pb.GetVideoListReq
	5, // 5: pb.VideoService.FeedVideos:input_type -> pb.FeedVideosReq
	7, // 6: pb.VideoService.GetMyFavoriteVideos:input_type -> pb.MyFavoriteVideosReq
	1, // 7: pb.VideoService.PubVideo:output_type -> pb.PubVideoResp
	4, // 8: pb.VideoService.GetVideoList:output_type -> pb.GetVideoListResp
	6, // 9: pb.VideoService.FeedVideos:output_type -> pb.FeedVideosResp
	8, // 10: pb.VideoService.GetMyFavoriteVideos:output_type -> pb.MyFavoriteVideosResp
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_VideoService_proto_init() }
func file_VideoService_proto_init() {
	if File_VideoService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_VideoService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubVideoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_VideoService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubVideoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_VideoService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Video); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_VideoService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVideoListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_VideoService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVideoListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_VideoService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedVideosReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_VideoService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedVideosResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_VideoService_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyFavoriteVideosReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_VideoService_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyFavoriteVideosResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_VideoService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_VideoService_proto_goTypes,
		DependencyIndexes: file_VideoService_proto_depIdxs,
		MessageInfos:      file_VideoService_proto_msgTypes,
	}.Build()
	File_VideoService_proto = out.File
	file_VideoService_proto_rawDesc = nil
	file_VideoService_proto_goTypes = nil
	file_VideoService_proto_depIdxs = nil
}
