// Code generated by goctl. DO NOT EDIT!
// Source: UserOptService.proto

package server

import (
	"context"

	"douyin/service/rpc-user-operate/internal/logic"
	"douyin/service/rpc-user-operate/internal/svc"
	"douyin/service/rpc-user-operate/userOptPb"
)

type UserOptServiceServer struct {
	svcCtx *svc.ServiceContext
	userOptPb.UnimplementedUserOptServiceServer
}

func NewUserOptServiceServer(svcCtx *svc.ServiceContext) *UserOptServiceServer {
	return &UserOptServiceServer{
		svcCtx: svcCtx,
	}
}

// -----------------------userFavoriteList-----------------------
func (s *UserOptServiceServer) GetUserFavorite(ctx context.Context, in *userOptPb.GetUserFavoriteReq) (*userOptPb.GetUserFavoriteResp, error) {
	l := logic.NewGetUserFavoriteLogic(ctx, s.svcCtx)
	return l.GetUserFavorite(in)
}

func (s *UserOptServiceServer) GetUserFollow(ctx context.Context, in *userOptPb.GetUserFollowReq) (*userOptPb.GetUserFollowResp, error) {
	l := logic.NewGetUserFollowLogic(ctx, s.svcCtx)
	return l.GetUserFollow(in)
}

func (s *UserOptServiceServer) UpdateFavoriteStatus(ctx context.Context, in *userOptPb.UpdateFavoriteStatusReq) (*userOptPb.UpdateFavoriteStatusResp, error) {
	l := logic.NewUpdateFavoriteStatusLogic(ctx, s.svcCtx)
	return l.UpdateFavoriteStatus(in)
}

func (s *UserOptServiceServer) UpdateFollowStatus(ctx context.Context, in *userOptPb.UpdateFollowStatusReq) (*userOptPb.UpdateFollowStatusResp, error) {
	l := logic.NewUpdateFollowStatusLogic(ctx, s.svcCtx)
	return l.UpdateFollowStatus(in)
}

func (s *UserOptServiceServer) UpdateCommentStatus(ctx context.Context, in *userOptPb.UpdateCommentStatusReq) (*userOptPb.UpdateCommentStatusResp, error) {
	l := logic.NewUpdateCommentStatusLogic(ctx, s.svcCtx)
	return l.UpdateCommentStatus(in)
}

func (s *UserOptServiceServer) GetVideoComment(ctx context.Context, in *userOptPb.GetVideoCommentReq) (*userOptPb.GetVideoCommentReqResp, error) {
	l := logic.NewGetVideoCommentLogic(ctx, s.svcCtx)
	return l.GetVideoComment(in)
}

func (s *UserOptServiceServer) GetUserFollower(ctx context.Context, in *userOptPb.GetUserFollowerReq) (*userOptPb.GetUserFollowerResp, error) {
	l := logic.NewGetUserFollowerLogic(ctx, s.svcCtx)
	return l.GetUserFollower(in)
}
