// Code generated by goctl. DO NOT EDIT!
// Source: UserOptService.proto

package server

import (
	"context"

	"douyin/service/rpc-user-operate/internal/logic"
	"douyin/service/rpc-user-operate/internal/svc"
	"douyin/service/rpc-user-operate/userOptPb"
)

type UserOptServiceServer struct {
	svcCtx *svc.ServiceContext
	userOptPb.UnimplementedUserOptServiceServer
}

func NewUserOptServiceServer(svcCtx *svc.ServiceContext) *UserOptServiceServer {
	return &UserOptServiceServer{
		svcCtx: svcCtx,
	}
}

// -----------------------userFavoriteList-----------------------
func (s *UserOptServiceServer) AddFavorite(ctx context.Context, in *userOptPb.AddFavoriteReq) (*userOptPb.AddFavoriteResp, error) {
	l := logic.NewAddFavoriteLogic(ctx, s.svcCtx)
	return l.AddFavorite(in)
}

func (s *UserOptServiceServer) CancelFavorite(ctx context.Context, in *userOptPb.CancelFavoriteResp) (*userOptPb.CancelFavoriteResp, error) {
	l := logic.NewCancelFavoriteLogic(ctx, s.svcCtx)
	return l.CancelFavorite(in)
}

func (s *UserOptServiceServer) GetUserFavorite(ctx context.Context, in *userOptPb.GetUserFavoriteReq) (*userOptPb.GetUserFavoriteResp, error) {
	l := logic.NewGetUserFavoriteLogic(ctx, s.svcCtx)
	return l.GetUserFavorite(in)
}

func (s *UserOptServiceServer) GetUserFollow(ctx context.Context, in *userOptPb.GetUserFollowReq) (*userOptPb.GetUserFollowResp, error) {
	l := logic.NewGetUserFollowLogic(ctx, s.svcCtx)
	return l.GetUserFollow(in)
}
