// Code generated by goctl. DO NOT EDIT!
// Source: VideoService.proto

package server

import (
	"context"

	"douyin/service/rpc-video-service/internal/logic"
	"douyin/service/rpc-video-service/internal/svc"
	"douyin/service/rpc-video-service/videoSvcPb"
)

type VideoServiceServer struct {
	svcCtx *svc.ServiceContext
	videoSvcPb.UnimplementedVideoServiceServer
}

func NewVideoServiceServer(svcCtx *svc.ServiceContext) *VideoServiceServer {
	return &VideoServiceServer{
		svcCtx: svcCtx,
	}
}

// -----------------------video-----------------------
func (s *VideoServiceServer) PubVideo(ctx context.Context, in *videoSvcPb.PubVideoReq) (*videoSvcPb.PubVideoResp, error) {
	l := logic.NewPubVideoLogic(ctx, s.svcCtx)
	return l.PubVideo(in)
}

func (s *VideoServiceServer) GetVideoList(ctx context.Context, in *videoSvcPb.GetVideoListReq) (*videoSvcPb.GetVideoListResp, error) {
	l := logic.NewGetVideoListLogic(ctx, s.svcCtx)
	return l.GetVideoList(in)
}

func (s *VideoServiceServer) FeedVideos(ctx context.Context, in *videoSvcPb.FeedVideosReq) (*videoSvcPb.FeedVideosResp, error) {
	l := logic.NewFeedVideosLogic(ctx, s.svcCtx)
	return l.FeedVideos(in)
}

func (s *VideoServiceServer) GetMyFavoriteVideos(ctx context.Context, in *videoSvcPb.MyFavoriteVideosReq) (*videoSvcPb.MyFavoriteVideosResp, error) {
	l := logic.NewGetMyFavoriteVideosLogic(ctx, s.svcCtx)
	return l.GetMyFavoriteVideos(in)
}
