// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"douyin/common/globalkey"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	videoFieldNames          = builder.RawFieldNames(&Video{})
	videoRows                = strings.Join(videoFieldNames, ",")
	videoRowsExpectAutoSet   = strings.Join(stringx.Remove(videoFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	videoRowsWithPlaceHolder = strings.Join(stringx.Remove(videoFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheDouyin2VideoIdPrefix = "cache:douyin2:video:id:"
)

type (
	videoModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Video) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Video, error)
		Update(ctx context.Context, session sqlx.Session, data *Video) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Video) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultVideoModel struct {
		sqlc.CachedConn
		table string
	}

	Video struct {
		Id            int64     `db:"id"`
		AuthId        int64     `db:"auth_id"`
		Title         string    `db:"title"`
		PlayURL       string    `db:"play_URL"`
		CoverURL      string    `db:"cover_URL"`
		FavoriteCount int64     `db:"favorite_count"`
		CommentCount  int64     `db:"comment_count"`
		CreateTime    time.Time `db:"create_time"`
		DelState      int64     `db:"del_state"`
		IsFavorite    int64     `db:"is_favorite"`
	}
)

func newVideoModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultVideoModel {
	return &defaultVideoModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`video`",
	}
}

func (m *defaultVideoModel) Insert(ctx context.Context, session sqlx.Session, data *Video) (sql.Result, error) {
	douyin2VideoIdKey := fmt.Sprintf("%s%v", cacheDouyin2VideoIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, videoRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.AuthId, data.Title, data.PlayURL, data.CoverURL, data.FavoriteCount, data.CommentCount, data.DelState, data.IsFavorite)
		}
		return conn.ExecCtx(ctx, query, data.AuthId, data.Title, data.PlayURL, data.CoverURL, data.FavoriteCount, data.CommentCount, data.DelState, data.IsFavorite)
	}, douyin2VideoIdKey)
}

func (m *defaultVideoModel) FindOne(ctx context.Context, id int64) (*Video, error) {
	douyin2VideoIdKey := fmt.Sprintf("%s%v", cacheDouyin2VideoIdPrefix, id)
	var resp Video
	err := m.QueryRowCtx(ctx, &resp, douyin2VideoIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", videoRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVideoModel) Update(ctx context.Context, session sqlx.Session, data *Video) (sql.Result, error) {
	douyin2VideoIdKey := fmt.Sprintf("%s%v", cacheDouyin2VideoIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, videoRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.AuthId, data.Title, data.PlayURL, data.CoverURL, data.FavoriteCount, data.CommentCount, data.DelState, data.IsFavorite, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.AuthId, data.Title, data.PlayURL, data.CoverURL, data.FavoriteCount, data.CommentCount, data.DelState, data.IsFavorite, data.Id)
	}, douyin2VideoIdKey)
}

func (m *defaultVideoModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Video) error {

	return nil

}

func (m *defaultVideoModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	douyin2VideoIdKey := fmt.Sprintf("%s%v", cacheDouyin2VideoIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, douyin2VideoIdKey)
	return err
}

func (m *defaultVideoModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheDouyin2VideoIdPrefix, primary)
}
func (m *defaultVideoModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", videoRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultVideoModel) tableName() string {
	return m.table
}
