// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: UserOptService.proto

package userOptPb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserOptServiceClient is the client API for UserOptService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserOptServiceClient interface {
	//-----------------------userFavoriteList-----------------------
	GetUserFavorite(ctx context.Context, in *GetUserFavoriteReq, opts ...grpc.CallOption) (*GetUserFavoriteResp, error)
	GetUserFollow(ctx context.Context, in *GetUserFollowReq, opts ...grpc.CallOption) (*GetUserFollowResp, error)
	UpdateFavoriteStatus(ctx context.Context, in *UpdateFavoriteStatusReq, opts ...grpc.CallOption) (*UpdateFavoriteStatusResp, error)
	UpdateFollowStatus(ctx context.Context, in *UpdateFollowStatusReq, opts ...grpc.CallOption) (*UpdateFollowStatusResp, error)
	UpdateCommentStatus(ctx context.Context, in *UpdateCommentStatusReq, opts ...grpc.CallOption) (*UpdateCommentStatusResp, error)
	GetVideoComment(ctx context.Context, in *GetVideoCommentReq, opts ...grpc.CallOption) (*GetVideoCommentReqResp, error)
	GetUserFollower(ctx context.Context, in *GetUserFollowerReq, opts ...grpc.CallOption) (*GetUserFollowerResp, error)
}

type userOptServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserOptServiceClient(cc grpc.ClientConnInterface) UserOptServiceClient {
	return &userOptServiceClient{cc}
}

func (c *userOptServiceClient) GetUserFavorite(ctx context.Context, in *GetUserFavoriteReq, opts ...grpc.CallOption) (*GetUserFavoriteResp, error) {
	out := new(GetUserFavoriteResp)
	err := c.cc.Invoke(ctx, "/pb.UserOptService/GetUserFavorite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOptServiceClient) GetUserFollow(ctx context.Context, in *GetUserFollowReq, opts ...grpc.CallOption) (*GetUserFollowResp, error) {
	out := new(GetUserFollowResp)
	err := c.cc.Invoke(ctx, "/pb.UserOptService/GetUserFollow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOptServiceClient) UpdateFavoriteStatus(ctx context.Context, in *UpdateFavoriteStatusReq, opts ...grpc.CallOption) (*UpdateFavoriteStatusResp, error) {
	out := new(UpdateFavoriteStatusResp)
	err := c.cc.Invoke(ctx, "/pb.UserOptService/UpdateFavoriteStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOptServiceClient) UpdateFollowStatus(ctx context.Context, in *UpdateFollowStatusReq, opts ...grpc.CallOption) (*UpdateFollowStatusResp, error) {
	out := new(UpdateFollowStatusResp)
	err := c.cc.Invoke(ctx, "/pb.UserOptService/UpdateFollowStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOptServiceClient) UpdateCommentStatus(ctx context.Context, in *UpdateCommentStatusReq, opts ...grpc.CallOption) (*UpdateCommentStatusResp, error) {
	out := new(UpdateCommentStatusResp)
	err := c.cc.Invoke(ctx, "/pb.UserOptService/UpdateCommentStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOptServiceClient) GetVideoComment(ctx context.Context, in *GetVideoCommentReq, opts ...grpc.CallOption) (*GetVideoCommentReqResp, error) {
	out := new(GetVideoCommentReqResp)
	err := c.cc.Invoke(ctx, "/pb.UserOptService/GetVideoComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userOptServiceClient) GetUserFollower(ctx context.Context, in *GetUserFollowerReq, opts ...grpc.CallOption) (*GetUserFollowerResp, error) {
	out := new(GetUserFollowerResp)
	err := c.cc.Invoke(ctx, "/pb.UserOptService/GetUserFollower", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserOptServiceServer is the server API for UserOptService service.
// All implementations must embed UnimplementedUserOptServiceServer
// for forward compatibility
type UserOptServiceServer interface {
	//-----------------------userFavoriteList-----------------------
	GetUserFavorite(context.Context, *GetUserFavoriteReq) (*GetUserFavoriteResp, error)
	GetUserFollow(context.Context, *GetUserFollowReq) (*GetUserFollowResp, error)
	UpdateFavoriteStatus(context.Context, *UpdateFavoriteStatusReq) (*UpdateFavoriteStatusResp, error)
	UpdateFollowStatus(context.Context, *UpdateFollowStatusReq) (*UpdateFollowStatusResp, error)
	UpdateCommentStatus(context.Context, *UpdateCommentStatusReq) (*UpdateCommentStatusResp, error)
	GetVideoComment(context.Context, *GetVideoCommentReq) (*GetVideoCommentReqResp, error)
	GetUserFollower(context.Context, *GetUserFollowerReq) (*GetUserFollowerResp, error)
	mustEmbedUnimplementedUserOptServiceServer()
}

// UnimplementedUserOptServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserOptServiceServer struct {
}

func (UnimplementedUserOptServiceServer) GetUserFavorite(context.Context, *GetUserFavoriteReq) (*GetUserFavoriteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFavorite not implemented")
}
func (UnimplementedUserOptServiceServer) GetUserFollow(context.Context, *GetUserFollowReq) (*GetUserFollowResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFollow not implemented")
}
func (UnimplementedUserOptServiceServer) UpdateFavoriteStatus(context.Context, *UpdateFavoriteStatusReq) (*UpdateFavoriteStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFavoriteStatus not implemented")
}
func (UnimplementedUserOptServiceServer) UpdateFollowStatus(context.Context, *UpdateFollowStatusReq) (*UpdateFollowStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFollowStatus not implemented")
}
func (UnimplementedUserOptServiceServer) UpdateCommentStatus(context.Context, *UpdateCommentStatusReq) (*UpdateCommentStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCommentStatus not implemented")
}
func (UnimplementedUserOptServiceServer) GetVideoComment(context.Context, *GetVideoCommentReq) (*GetVideoCommentReqResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoComment not implemented")
}
func (UnimplementedUserOptServiceServer) GetUserFollower(context.Context, *GetUserFollowerReq) (*GetUserFollowerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFollower not implemented")
}
func (UnimplementedUserOptServiceServer) mustEmbedUnimplementedUserOptServiceServer() {}

// UnsafeUserOptServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserOptServiceServer will
// result in compilation errors.
type UnsafeUserOptServiceServer interface {
	mustEmbedUnimplementedUserOptServiceServer()
}

func RegisterUserOptServiceServer(s grpc.ServiceRegistrar, srv UserOptServiceServer) {
	s.RegisterService(&UserOptService_ServiceDesc, srv)
}

func _UserOptService_GetUserFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserFavoriteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOptServiceServer).GetUserFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserOptService/GetUserFavorite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOptServiceServer).GetUserFavorite(ctx, req.(*GetUserFavoriteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOptService_GetUserFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserFollowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOptServiceServer).GetUserFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserOptService/GetUserFollow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOptServiceServer).GetUserFollow(ctx, req.(*GetUserFollowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOptService_UpdateFavoriteStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFavoriteStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOptServiceServer).UpdateFavoriteStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserOptService/UpdateFavoriteStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOptServiceServer).UpdateFavoriteStatus(ctx, req.(*UpdateFavoriteStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOptService_UpdateFollowStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFollowStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOptServiceServer).UpdateFollowStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserOptService/UpdateFollowStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOptServiceServer).UpdateFollowStatus(ctx, req.(*UpdateFollowStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOptService_UpdateCommentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOptServiceServer).UpdateCommentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserOptService/UpdateCommentStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOptServiceServer).UpdateCommentStatus(ctx, req.(*UpdateCommentStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOptService_GetVideoComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOptServiceServer).GetVideoComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserOptService/GetVideoComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOptServiceServer).GetVideoComment(ctx, req.(*GetVideoCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserOptService_GetUserFollower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserFollowerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserOptServiceServer).GetUserFollower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserOptService/GetUserFollower",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserOptServiceServer).GetUserFollower(ctx, req.(*GetUserFollowerReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserOptService_ServiceDesc is the grpc.ServiceDesc for UserOptService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserOptService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserOptService",
	HandlerType: (*UserOptServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserFavorite",
			Handler:    _UserOptService_GetUserFavorite_Handler,
		},
		{
			MethodName: "GetUserFollow",
			Handler:    _UserOptService_GetUserFollow_Handler,
		},
		{
			MethodName: "UpdateFavoriteStatus",
			Handler:    _UserOptService_UpdateFavoriteStatus_Handler,
		},
		{
			MethodName: "UpdateFollowStatus",
			Handler:    _UserOptService_UpdateFollowStatus_Handler,
		},
		{
			MethodName: "UpdateCommentStatus",
			Handler:    _UserOptService_UpdateCommentStatus_Handler,
		},
		{
			MethodName: "GetVideoComment",
			Handler:    _UserOptService_GetVideoComment_Handler,
		},
		{
			MethodName: "GetUserFollower",
			Handler:    _UserOptService_GetUserFollower_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "UserOptService.proto",
}
