// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: UserOptService.proto

package userOptPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户给视频点赞
type UpdateFavoriteStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId    int64 `protobuf:"varint,1,opt,name=videoId,proto3" json:"videoId,omitempty"`       //videoId
	UserId     int64 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`         //userId
	ActionType int64 `protobuf:"varint,3,opt,name=actionType,proto3" json:"actionType,omitempty"` //点赞
}

func (x *UpdateFavoriteStatusReq) Reset() {
	*x = UpdateFavoriteStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserOptService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFavoriteStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFavoriteStatusReq) ProtoMessage() {}

func (x *UpdateFavoriteStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_UserOptService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFavoriteStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateFavoriteStatusReq) Descriptor() ([]byte, []int) {
	return file_UserOptService_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateFavoriteStatusReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *UpdateFavoriteStatusReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateFavoriteStatusReq) GetActionType() int64 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

type UpdateFavoriteStatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateFavoriteStatusResp) Reset() {
	*x = UpdateFavoriteStatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserOptService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFavoriteStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFavoriteStatusResp) ProtoMessage() {}

func (x *UpdateFavoriteStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_UserOptService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFavoriteStatusResp.ProtoReflect.Descriptor instead.
func (*UpdateFavoriteStatusResp) Descriptor() ([]byte, []int) {
	return file_UserOptService_proto_rawDescGZIP(), []int{1}
}

// 获得用户和视频的点赞关系
type GetUserFavoriteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`            //userId
	VideoIds []int64 `protobuf:"varint,2,rep,packed,name=videoIds,proto3" json:"videoIds,omitempty"` //videoId
}

func (x *GetUserFavoriteReq) Reset() {
	*x = GetUserFavoriteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserOptService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserFavoriteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFavoriteReq) ProtoMessage() {}

func (x *GetUserFavoriteReq) ProtoReflect() protoreflect.Message {
	mi := &file_UserOptService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFavoriteReq.ProtoReflect.Descriptor instead.
func (*GetUserFavoriteReq) Descriptor() ([]byte, []int) {
	return file_UserOptService_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserFavoriteReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserFavoriteReq) GetVideoIds() []int64 {
	if x != nil {
		return x.VideoIds
	}
	return nil
}

type GetUserFavoriteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserFavoriteList map[int64]bool `protobuf:"bytes,1,rep,name=userFavoriteList,proto3" json:"userFavoriteList,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //userFavoriteList
	UserFavoriteArr  []int64        `protobuf:"varint,2,rep,packed,name=userFavoriteArr,proto3" json:"userFavoriteArr,omitempty"`                                                                                     //userFavoriteArr
}

func (x *GetUserFavoriteResp) Reset() {
	*x = GetUserFavoriteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserOptService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserFavoriteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFavoriteResp) ProtoMessage() {}

func (x *GetUserFavoriteResp) ProtoReflect() protoreflect.Message {
	mi := &file_UserOptService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFavoriteResp.ProtoReflect.Descriptor instead.
func (*GetUserFavoriteResp) Descriptor() ([]byte, []int) {
	return file_UserOptService_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserFavoriteResp) GetUserFavoriteList() map[int64]bool {
	if x != nil {
		return x.UserFavoriteList
	}
	return nil
}

func (x *GetUserFavoriteResp) GetUserFavoriteArr() []int64 {
	if x != nil {
		return x.UserFavoriteArr
	}
	return nil
}

// 获得用户的关注列表
type GetUserFollowReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`          //user_id
	AuthIds []int64 `protobuf:"varint,2,rep,packed,name=authIds,proto3" json:"authIds,omitempty"` //user_id
}

func (x *GetUserFollowReq) Reset() {
	*x = GetUserFollowReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserOptService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserFollowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFollowReq) ProtoMessage() {}

func (x *GetUserFollowReq) ProtoReflect() protoreflect.Message {
	mi := &file_UserOptService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFollowReq.ProtoReflect.Descriptor instead.
func (*GetUserFollowReq) Descriptor() ([]byte, []int) {
	return file_UserOptService_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserFollowReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserFollowReq) GetAuthIds() []int64 {
	if x != nil {
		return x.AuthIds
	}
	return nil
}

type GetUserFollowResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserFollowList map[int64]bool `protobuf:"bytes,1,rep,name=userFollowList,proto3" json:"userFollowList,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //用户和视频的关注关系
}

func (x *GetUserFollowResp) Reset() {
	*x = GetUserFollowResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserOptService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserFollowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFollowResp) ProtoMessage() {}

func (x *GetUserFollowResp) ProtoReflect() protoreflect.Message {
	mi := &file_UserOptService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFollowResp.ProtoReflect.Descriptor instead.
func (*GetUserFollowResp) Descriptor() ([]byte, []int) {
	return file_UserOptService_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserFollowResp) GetUserFollowList() map[int64]bool {
	if x != nil {
		return x.UserFollowList
	}
	return nil
}

// 获得视频的评论列表
type GetVideoCommentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId int64 `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"` //video_id
}

func (x *GetVideoCommentReq) Reset() {
	*x = GetVideoCommentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserOptService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoCommentReq) ProtoMessage() {}

func (x *GetVideoCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_UserOptService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoCommentReq.ProtoReflect.Descriptor instead.
func (*GetVideoCommentReq) Descriptor() ([]byte, []int) {
	return file_UserOptService_proto_rawDescGZIP(), []int{6}
}

func (x *GetVideoCommentReq) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type GetVideoCommentReqResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //video_id
}

func (x *GetVideoCommentReqResp) Reset() {
	*x = GetVideoCommentReqResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UserOptService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoCommentReqResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoCommentReqResp) ProtoMessage() {}

func (x *GetVideoCommentReqResp) ProtoReflect() protoreflect.Message {
	mi := &file_UserOptService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoCommentReqResp.ProtoReflect.Descriptor instead.
func (*GetVideoCommentReqResp) Descriptor() ([]byte, []int) {
	return file_UserOptService_proto_rawDescGZIP(), []int{7}
}

func (x *GetVideoCommentReqResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_UserOptService_proto protoreflect.FileDescriptor

var file_UserOptService_proto_rawDesc = []byte{
	0x0a, 0x14, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x6b, 0x0a, 0x17, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x48, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x46, 0x61,
	0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x49, 0x64, 0x73, 0x22, 0xdf, 0x01,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x59, 0x0a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x46, 0x61, 0x76,
	0x6f, 0x72, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2d, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x46, 0x61, 0x76, 0x6f,
	0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x46, 0x61, 0x76,
	0x6f, 0x72, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x10,
	0x75, 0x73, 0x65, 0x72, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x28, 0x0a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65,
	0x41, 0x72, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x46,
	0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x41, 0x72, 0x72, 0x1a, 0x43, 0x0a, 0x15, 0x55, 0x73,
	0x65, 0x72, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x44, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x75, 0x74, 0x68, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x61, 0x75,
	0x74, 0x68, 0x49, 0x64, 0x73, 0x22, 0xa9, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x51, 0x0a, 0x0e, 0x75,
	0x73, 0x65, 0x72, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x46,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0e,
	0x75, 0x73, 0x65, 0x72, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x41,
	0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x2f, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x49, 0x64, 0x22, 0x28, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x32, 0xe5, 0x01, 0x0a,
	0x0e, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x42, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69,
	0x74, 0x65, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x46,
	0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x46, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x51, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x61, 0x76, 0x6f, 0x72,
	0x69, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x46, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x4f, 0x70,
	0x74, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_UserOptService_proto_rawDescOnce sync.Once
	file_UserOptService_proto_rawDescData = file_UserOptService_proto_rawDesc
)

func file_UserOptService_proto_rawDescGZIP() []byte {
	file_UserOptService_proto_rawDescOnce.Do(func() {
		file_UserOptService_proto_rawDescData = protoimpl.X.CompressGZIP(file_UserOptService_proto_rawDescData)
	})
	return file_UserOptService_proto_rawDescData
}

var file_UserOptService_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_UserOptService_proto_goTypes = []interface{}{
	(*UpdateFavoriteStatusReq)(nil),  // 0: pb.UpdateFavoriteStatusReq
	(*UpdateFavoriteStatusResp)(nil), // 1: pb.UpdateFavoriteStatusResp
	(*GetUserFavoriteReq)(nil),       // 2: pb.GetUserFavoriteReq
	(*GetUserFavoriteResp)(nil),      // 3: pb.GetUserFavoriteResp
	(*GetUserFollowReq)(nil),         // 4: pb.GetUserFollowReq
	(*GetUserFollowResp)(nil),        // 5: pb.GetUserFollowResp
	(*GetVideoCommentReq)(nil),       // 6: pb.GetVideoCommentReq
	(*GetVideoCommentReqResp)(nil),   // 7: pb.GetVideoCommentReqResp
	nil,                              // 8: pb.GetUserFavoriteResp.UserFavoriteListEntry
	nil,                              // 9: pb.GetUserFollowResp.UserFollowListEntry
}
var file_UserOptService_proto_depIdxs = []int32{
	8, // 0: pb.GetUserFavoriteResp.userFavoriteList:type_name -> pb.GetUserFavoriteResp.UserFavoriteListEntry
	9, // 1: pb.GetUserFollowResp.userFollowList:type_name -> pb.GetUserFollowResp.UserFollowListEntry
	2, // 2: pb.UserOptService.GetUserFavorite:input_type -> pb.GetUserFavoriteReq
	4, // 3: pb.UserOptService.GetUserFollow:input_type -> pb.GetUserFollowReq
	0, // 4: pb.UserOptService.UpdateFavoriteStatus:input_type -> pb.UpdateFavoriteStatusReq
	3, // 5: pb.UserOptService.GetUserFavorite:output_type -> pb.GetUserFavoriteResp
	5, // 6: pb.UserOptService.GetUserFollow:output_type -> pb.GetUserFollowResp
	1, // 7: pb.UserOptService.UpdateFavoriteStatus:output_type -> pb.UpdateFavoriteStatusResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_UserOptService_proto_init() }
func file_UserOptService_proto_init() {
	if File_UserOptService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_UserOptService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFavoriteStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserOptService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFavoriteStatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserOptService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserFavoriteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserOptService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserFavoriteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserOptService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserFollowReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserOptService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserFollowResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserOptService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVideoCommentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_UserOptService_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVideoCommentReqResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_UserOptService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_UserOptService_proto_goTypes,
		DependencyIndexes: file_UserOptService_proto_depIdxs,
		MessageInfos:      file_UserOptService_proto_msgTypes,
	}.Build()
	File_UserOptService_proto = out.File
	file_UserOptService_proto_rawDesc = nil
	file_UserOptService_proto_goTypes = nil
	file_UserOptService_proto_depIdxs = nil
}
